config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers
  resources :orders, only: [ :index, :show ]
  resources :order_items

  resources :cart, only: [ :create, :destroy ] do
    patch :update_quantity, on: :member
  end

  resources :checkout, only: [ :index ] do
    patch "update_quantity/:id", to: "checkout#update_quantity", as: "update_quantity"
    get "confirm", on: :collection
  end

  get "checkout", to: "checkout#index", as: "checkout"

  get "checkout/thankyou", to: "checkout#thankyou", as: "thank_you_checkout"


  # Root path
  root to: "products#index"

  # Static page support route
  get "support/:page", to: "support#show", as: :static_page

  # Product routes
  resources :products do
    collection do
      get "filter_by_category"
    end
  end

  # Admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # PWA files
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :description, presence: true
  validates :description, length: { maximum: 500 }
  validates :name, length: { minimum: 3, maximum: 100 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :category
  validates :category, presence: true
  has_many :order_items
  has_many :orders, through: :order_items
  has_one_attached :image

  def self.search(query)
    if query.present?
      where("name LIKE ?", "%#{query}%")
    else
      all
    end
  end

  def self.ransackable_associations(auth_object = nil)
    [ "category" ]
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "category_id", "id", "in_stock", "name", "price", "created_at", "updated_at" ]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all.presence || []
    @products = Product.all.order(price: :asc)

    if params[:search].present?
      @products = @products.where("name LIKE ? OR description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")
    end

    if params[:category_id].present?
      @products = @products.where(category_id: params[:category_id])
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div class="column is-one-fifth">
  <div class="card fixed-size">
    <div class="element has-text-centered">
      <div class="bubble">
        <span class="tag is-warning m-3"><%= product.category.name %></span>
      </div>
    </div>
    <%= link_to product_path(product), class: 'card-link' do %>
      <% if product.image.attached? %>
        <div class="card-image">
          <figure class="image is-1by1">
            <%= image_tag(product.image, alt: "Product Image", class: "is-rounded") %>
          </figure>
        </div>
      <% end %>
    <% end %>

    <div class="card-content has-text-centered">
      <p class="title is-5 mb-1">
        <%= product.name %>
      </p>
      <p class="subtitle is-6 m-3">
        <strong><%= product.price %>$</strong>
      </p>
      <% if session[:cart]&.key?(product.id.to_s) %>
        <%= button_to cart_path(product), class: "button red-wine-button", style: "width: 100%;", method: :delete do %>
          Remove from cart
        <% end %>
      <% else %>
        <%= form_with url: cart_index_path, method: :post, local: true do %>
          <%= hidden_field_tag :id, product.id %>
          <%= button_tag "Add to cart", class: "button green-button", style: "width: 100%;" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="columns mt-3 ml-6">
  <div class="column is-two-thirds">
    <%= form_with url: products_path, method: :get, local: true, id: "search-form" do %>
      <div class="field is-inline-block m-2">
        <%= label_tag :search, "Products:", class: "label" %>
        <%= text_field_tag :search, params[:search], class: "input", placeholder: "Type Here..." %>
      </div>
      <div class="field is-inline-block m-2">
        <%= label_tag :category_id, "Category:", class: "label" %>
        <%= select_tag :category_id, options_from_collection_for_select(@categories, :id, :name, params[:category_id]), include_blank: "All", class: "select" %>
      </div>
      <div class="field is-inline-block m-2">
        <%= submit_tag "Search", class: "button is-primary" %>
      </div>
    <% end %>
  </div>
</div>


<div class="columns is-multiline m-6">
  <%= render partial: 'product', collection: @products, as: :product, locals: { show_link: true } %>
</div>

app/views/products/show.html.erb
<div class="columns m-6">
  <div class="column is-one-half">
    <div class="card">
      <% if @product.image.attached? %>
        <div class="card-image">
          <figure class="image is-1by1">
            <%= image_tag(@product.image, alt: "Product Image", class: "is-rounded") %>
          </figure>
        </div>
      <% end %>
    </div>
  </div>
  <div class="column">
    <p class="title is-3 mb-6">
      <strong><%= @product.name %></strong>
    </p>
    <p class="subtitle is-6">
      <strong>Price: <%= @product.price %>$</strong><br>
      <strong>Category: <%= @product.category.name %></strong><br>
      <strong>Description:<br><%= @product.description %></strong>
    </p>
    <div class="element">
      <%= link_to 'Add to cart', product_path(@product), class: 'button is-info m-2' %>
    </div>
  </div>
</div>