config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers
  resources :orders, only: [ :index, :show ]
  resources :order_items

  resources :cart, only: [ :create, :destroy ] do
    patch :update_quantity, on: :member
  end

  resources :checkout, only: [ :index ] do
    patch "update_quantity/:id", to: "checkout#update_quantity", as: "update_quantity"
    get "confirm", on: :collection
  end

  get "checkout", to: "checkout#index", as: "checkout"

  get "checkout/thankyou", to: "checkout#thankyou", as: "thank_you_checkout"


  # Root path
  root to: "products#index"

  # Static page support route
  get "support/:page", to: "support#show", as: :static_page

  # Product routes
  resources :products do
    collection do
      get "filter_by_category"
    end
  end

  # Admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # PWA files
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/about.rb
class About < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    ["content", "created_at", "id", "title", "updated_at"]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at" ]
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :products

  def self.ransackable_associations(auth_object = nil)
    [ "products" ]
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "created_at", "id", "name", "updated_at" ]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  def self.ransackable_attributes(auth_object = nil)
    [ "content", "created_at", "id", "title", "updated_at" ]
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :orders
  validates :name, :street_address, :city, :province, presence: true
  validates :postal_code, format: { with: /\A[A-Za-z]\d[A-Za-z] \d[A-Za-z]\d\z/, message: "must be in the format A1A 1A1" }, allow_blank: false

  def self.ransackable_associations(auth_object = nil)
    [ "orders" ]
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "id", "name", "email", "postal_code", "street_address", "city", "created_at", "updated_at", "reset_password_token", "province" ]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items
  has_many :products, through: :order_items
  validates :status, :payment, :cost, presence: true
  validates :payment, numericality: { only_integer: true }
  validates :cost, numericality: { greater_than_or_equal_to: 0 }

  def self.ransackable_attributes(auth_object = nil)
    [ "cost", "created_at", "customer_id", "id", "status", "updated_at" ]
  end

  def self.ransackable_associations(auth_object = nil)
    [ "customer", "order_items", "products" ]
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :price, :description, presence: true
  validates :description, length: { maximum: 500 }
  validates :name, length: { minimum: 3, maximum: 100 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  belongs_to :category
  validates :category, presence: true
  has_many :order_items
  has_many :orders, through: :order_items
  has_one_attached :image

  def self.search(query)
    if query.present?
      where("name LIKE ?", "%#{query}%")
    else
      all
    end
  end

  def self.ransackable_associations(auth_object = nil)
    [ "category" ]
  end

  def self.ransackable_attributes(auth_object = nil)
    [ "category_id", "id", "in_stock", "name", "price", "created_at", "updated_at" ]
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :get_product, only: %i[create destroy]

  def create
    product_id = @product.id.to_s
    session[:cart][product_id] ||= 0
    session[:cart][product_id] += 1
    redirect_to request.referer || root_path
  end

  def destroy
    product_id = @product.id.to_s
    session[:cart].delete(product_id)
    redirect_to request.referer || root_path
  end


  def update_quantity
    product_id = params[:id]
    quantity = params[:quantity].to_i
    session[:cart][product_id] = quantity if quantity > 0
    redirect_to request.referer || root_path
  end

  def cart
    session[:cart]&.map do |product_id, quantity|
      product = Product.find_by(id: product_id)
      next unless product
      { product: product, quantity: quantity }
    end.compact || []
  end

  private

  def get_product
    product_id = params[:id]
    @product = Product.find_by(id: product_id)

    unless @product
      redirect_to root_path, alert: "Product not found"
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders.includes(:order_items, :products)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_tax_rate(province)
    {
      "Alberta" => 0.05,
      "British Columbia" => 0.12,
      "Manitoba" => 0.12,
      "New Brunswick" => 0.15,
      "Newfoundland and Labrador" => 0.15,
      "Nova Scotia" => 0.15,
      "Ontario" => 0.13,
      "Prince Edward Island" => 0.15,
      "Quebec" => 0.14975,
      "Saskatchewan" => 0.06
    }[province] || 0.15
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="nav_title"><%= content_for(:title) || "XMass Deals" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "bulma", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application_custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="/assets/rails-ujs.js"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class='hero is-fullheight'>
      <div>
        <header class="navbar container">
          <div class="navbar-brand">
            <a class="navbar-item" href="/">
              <h1 class="is-size-4 has-text-weight-bold has-text-white">
                XMass Deals
              </h1>
            </a>
          </div>

          <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
              <a class="navbar-item" href="/support/about">
                About
              </a>
              <a class="navbar-item" href="/support/contact">
                Contact
              </a>
            </div>
            <div class="navbar-end">
              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to image_tag("traineau.jpg", style: "width: 50px; height: 50px; object-fit: cover;"), "#", class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <ul class="ml-3">
                    <% if cart.present? %>
                      <% cart.each do |entry| %>
                        <li style="width: 200px;">
                          <%= entry[:product].name %>
                          <div class="field has-addons">
                            <div class="control">
                              <%= form_with url: update_quantity_cart_path(entry[:product]), method: :patch, local: true do |form| %>
                                <%= form.number_field :quantity, value: entry[:quantity], min: 1, class: "input is-small", style: "width: 60px;" %>
                                <%= form.submit "Update", class: "button is-small is-info" %>
                              <% end %>
                            </div>
                            <div class="control mb-2 mr-2">
                              <%= link_to '❌', cart_path(entry[:product]), method: :delete, class: "button is-small is-danger" %>
                            </div>
                          </div>
                        </li>
                      <% end %>
                    <% else %>
                      <p>Your cart is empty.</p>
                    <% end %>
                  </ul>
                </div>
              </div>
              <a class="navbar-item">
                <% if customer_signed_in? %>
                  <%= link_to "Go to Checkout", checkout_path, class: "button is-primary is-light m-2" %>
                  <%= link_to "Go to Orders", orders_path, class: "button is-primary is-light m-2" %>
                  <%= link_to 'Sign Out', destroy_customer_session_path, method: :delete, class: "button is-danger is-light m-2" %>
                <% else %>
                  <%= link_to 'Sign In', new_customer_session_path, class: "button is-primary is-light m-2" %>
                <% end %>
              </a>
            </div>
          </div>
        </header>
        <main>
          <%= yield %>
        </main>
        <footer class="mt-6">
          <hr>
          <p class="has-text-centered m-6">XMass deals - Copyright <%= Time.current.year %></p>
        </footer>
      </div>
    </div>
  </body>
</html>